Repository Anti-VibeCoders/vibe, pull requests merged in 2025-09, with the labels that each got.

#68 feat: add GitHub issue templates for bugs, features, and questions
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: enhancement

#69 Apis back
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
  backend/app_vibe/services/supabase_service.py
  backend/app_vibe/urls.py
  backend/app_vibe/view/gemini_views.py
  backend/app_vibe/view/user_views.py
Labels: refactor

#70 Background api
  .env.example
  backend/app_vibe/serializer.py
  backend/app_vibe/services/supabase_service.py
  backend/app_vibe/view/user_views.py
Labels: enhancement

#72 fix: Renombramientos de tablas, serializer
  backend/app_vibe/migrations/0014_rename_backgrounduser_banneruser.py
  backend/app_vibe/models.py
  backend/app_vibe/serializer.py
  backend/app_vibe/view/user_views.py
Labels: fix

#73 feat: add new endpoints in backend for banners, also refactor the code following PEP8 rules
  .env.example
  backend/app_vibe/migrations/0014_rename_backgrounduser_banneruser.py
  backend/app_vibe/models.py
  backend/app_vibe/serializer.py
  backend/app_vibe/services/supabase_service.py
  backend/app_vibe/urls.py
  backend/app_vibe/view/coments_views.py
  backend/app_vibe/view/gemini_views.py
  backend/app_vibe/view/publication_views.py
  backend/app_vibe/view/user_views.py
  src/pages/features/comments/components/CardComment.tsx
  src/pages/features/comments/components/CreateComment.tsx
  src/pages/features/comments/components/PostInfo.tsx
  src/pages/features/comments/data/comments.ts
  src/pages/features/comments/data/post.ts
  src/pages/features/comments/pages/Comments.tsx
Labels: enhancement
